--      ******** NOTAÇÕES :RESTRIÇÕES **********
-------------------------------------------------------
---------------------CHAVE PRIMÁRIA
-------------------------------------------------------
--#01 CHAVE PRIMÁRIA COM NOME ATRIBUÍDO PELO SGBD
CREATE TABLE EMPREGADO (
    CPF VARCHAR (14) PRIMARY KEY
);

--#02 CHAVE PRIMÁRIA COM NOME ESPECÍFICADO
CREATE TABLE (
    CPF VARCHAR (14),
    CONSTRAINT EMPREGADO_PK PRIMARY KEY (CPF)
);
--#03 ADICIONAR RESTRIÇÃO CASO NÃO EXISTA
ALTER TABLE EMPREGADO
ADD CONSTRAINT EMPREGADO_PK PRIMARY KEY (CPF);
--#04 REMOVER A RESTRIÇÃO NÃO REMOVE A COLUNA
ALTER TABLE EMPREGADO
DROP CONSTRAINT EMPREGADO_PK;